template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "sms"
__UND2C_TRG__ = "mul"
__UNDEFINED_SOURCE__ = "Skolt Saami"
__UNDEFINED_TARGET__ = "Multiple languages"
__UND_SRC__ = "sms"
__UND_TRG__ = "mul"
